run_test echo_E.test
run_test echo_E_backslash3.test
run_test echo_bad_option1.test
run_test echo_e.test
run_test echo_e_backslash2.test
run_test echo_many_e_E1.test
run_test echo_simple.test
run_test echo_E_backslash1.test
run_test echo_EeE.test
run_test echo_bad_option2.test
run_test echo_eEe.test
run_test echo_e_backslash3.test
run_test echo_many_e_E2.test
run_test two_echos.test
run_test echo_E_backslash2.test  
run_test echo_args.test 
run_test echo_big_args.test
run_test echo_e_backslash1.test
run_test echo_many_args.test 
run_test echo_n.test
run_test echo_many_eE_in_one_option.test
run_test echo_ecolle.test
