run_test many_commands1.test
run_test many_commands2.test  
run_test two_commands_terminating_with_semicolon.test
run_test two_commands_terminating_witout_semicolon.test  
run_test twos_commands_with_space.test
